language: node_js
node_js: node
cache:
  npm: false
before_script:
- npm install -g gitbook-cli
script: 
- gitbook install
- gitbook build
- cp icons/* _book/gitbook/images
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  # committer_from_gh: true
  # allow_empty_commit: true
  github_token:
    secure: gLZ1JYCpUQatCth2IbRI09nT42ufy4UhM8G7sBoRkajae5xMibkhWja7//UZZwC/5vPp7FuHgacmLp1WfpfQGNwRtPBB7Dn8PlPHyjVFg4HEpXfq9YP2Q0236f0FI0H+KzGY+lWGjRq+RWJwIKY/Ehn1HL+njzRwDC/HxhX+sA10sf5vhrD7CMOxezGKQRCdpcIn58l2ujuJOTJN1YBmeYa1YK11UI8JJL61ZawrcFQ8WNqJqBJ5NLtt8JPumLoRxSzzFO0KpooZgDMQMJvmGi0VLrHhBzk+UOApwhy/NZnIJ7ddyfwWZB4pSa0LVIh6gHV1gpy/feVSEUQ+Vs/nA7Ho6uHV6GhI6kpEbv+POjwCVuDgz6Sx8ILtmiDfrDdIpdpt4XpO19Ji2DQon8ldflXVfZ4LJgog4D5B/RSMf7YEeUBAnphsVTCtCIrz63Uv2FtgCnvLHFClnFSdANy+o3DudUXBOk2HGkdzXdAHceU9R56u441JFdW6DakB3JVn1osNv8/+quH7LWTMpf6czP9xcvnDhnccu2mgvzfKM7K6S2yn3Q+Punmtf586E9N02AGOV8g00jzmwb56gJ5TdQwinB7b16vkJKwXVQAaIBgkAfgyIefCJKXERmzbL/ny55hrIBZv6nObPa6XNjF/IAtlBJ9ISO7miFb3pxofPic=
